# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: I'm hiding behind my keyboard - My journey through Makers Academy Web Dev Course....
email: fmlharrison@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In this blog I will document my rather stupid choice to put myself through the (supposed) hell that is the Makers Academy Wed Development Immersive Course. Over the next 16 weeks I will be writing about the highs, lows, ins, out and shake it all abouts of my journey. How many coffee and Red Bulls will I drink? Keep reading to find out!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: fmlharrison
github_username:  fmlharrison

# Build settings
markdown: kramdown
theme: minima
